app:
  environment: development
  port: "8080"
  version: "1.0.0"

database:
  host: localhost
  port: 3306
  username: apiuser
  password: apipassword
  database: storage-service

minio:
  endpoint: localhost:9000
  access_key: minioadmin
  secret_key: minioadmin
  use_ssl: false
  bucket_name: files
  region: us-east-1

jwt:
  jwks_cache_ttl: 1h
  jwks_timeout: 10s
  allowed_algorithms:
    - RS256
    - ES256
  clock_skew: 5m
  issuers: []
    # Example configuration for multiple identity providers
    # - name: auth0
    #   issuer: https://your-tenant.auth0.com/
    #   audience:
    #     - your-api-identifier
    #   jwks_url: https://your-tenant.auth0.com/.well-known/jwks.json
    #   username_claim: email
    #   roles_claim: https://your-app.com/roles
    # - name: firebase
    #   issuer: https://securetoken.google.com/your-project-id
    #   audience:
    #     - your-project-id
    #   jwks_url: https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com
    #   username_claim: email
    #   roles_claim: custom_claims

rate_limit:
  requests_per_minute: 100
  burst_size: 10
  ip_whitelist: []
  enable_redis: false
  user_based_limit: true

log:
  level: info
  format: json
  output_file: logs/app.log
  output_console: true
  max_size: 100
  max_age: 30
  max_backups: 5
  compress: true
