-- CREATE FILES TABLE
   CREATE TABLE IF NOT EXISTS `FILES` (
       `ID` CHAR(36) NOT NULL PRIMARY KEY,
       `USER_ID` CHAR(36) NOT NULL,
       `ORIGINAL_NAME` VARCHAR(255) NOT NULL,
       `STORED_NAME` VARCHAR(255) NOT NULL,
       `FILE_PATH` VARCHAR(500) NOT NULL,
       `FILE_SIZE` BIGINT NOT NULL,
       `MIME_TYPE` VARCHAR(100) NOT NULL,
       `CHECKSUM` VARCHAR(64),
       `BUCKET_NAME` VARCHAR(100) NOT NULL,
       `IS_PUBLIC` BOOLEAN DEFAULT FALSE,
       `METADATA` JSON,
       `CREATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
       `CREATED_BY` CHAR(36) NOT NULL,
       `UPDATED_BY` CHAR(36) NOT NULL,
       `UPDATED_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
       `DELETED_AT` TIMESTAMP NULL,

       -- INDEXES FOR PERFORMANCE
       INDEX `IDX_USER_ID` (`USER_ID`),
       INDEX `IDX_STORED_NAME` (`STORED_NAME`),
       INDEX `IDX_CREATED_AT` (`CREATED_AT`),
       INDEX `IDX_DELETED_AT` (`DELETED_AT`)
   ) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_UNICODE_CI;